export const reports = [
  {
    key: "13",
    short_title: "Report 13 (24-28 Feb)",
    title: "Weekly Outlook Report 13",
    subtitle: "24-28 Feb, 2025",
    date: "2025-02-28",
    pdf: "/reports/report13.pdf"
  },
  {
    key: "12",
    short_title: "Report 12 (17-22 Feb)",
    title: "Weekly Outlook Report 12",
    subtitle: "17-22 Feb, 2025",
    date: "2025-02-22",
    pdf: "/reports/report12.pdf"
  },
  {
    key: "11",
    short_title: "Report 11 (10-14 Feb)",
    title: "Weekly Outlook Report 11",
    subtitle: "10-14 Feb, 2025",
    date: "2025-02-14",
    pdf: "/reports/report11.pdf"
  },
]

export const members = [
  {
    linkedin: "https://www.linkedin.com/in/ioannis-stafylidis/",
    key: 1,
    img: "/giannis.jpg",
    name: "Giannis Stafilidis",
    role: "President",
    bio: "As the President of the Board of Directors of our organization, I am a graduate of the Department of International and European Studies at the University of Macedonia and currently an undergraduate student at the Faculty of Law at Aristotle University of Thessaloniki. At the same time, I work as a Marketing Manager at Asklipios Medica, contributing to the development of promotional strategies for private enterprises. My journey within the organization has introduced me to the key values of responsibility and solidarity, while my previous tenure as a Marketing Manager highlighted the constant need to analyze external business environment stimuli and continuously improve the organization's public image. Ultimately, having participated in numerous volunteer organizations and institutions, my goal is the continuous improvement of INEFAN's work quality through ongoing initiatives and training programs for its members, enabling them to meet the modern challenges of the workplace and the business world.",
  },
  {
    linkedin: "https://www.linkedin.com/in/elli-tsikrika/",
    key: 2,
    img: "/elli.jpg",
    name: "Elli Tsikrika",
    role: "Head of Human Resources",
    bio: "As a professional in the field of Human Resources, I first came into contact with the organization about three years ago during my studies in the MSc in Human Resource Management at the University of Macedonia. Having already completed my studies in the Department of International and European Studies, I currently serve as the Team Leader of the HR department at INEFAN while also working as an HR Manager at one of the largest IT companies, Lancom. Additionally, I oversee the recruitment process for Battlenet, which is part of the same group. My passion for human resource management has led me to the position I hold today, while my volunteer work at INEFAN provided me with the opportunity to connect with my current employers. Finally, without a doubt, I feel it is my duty to share my knowledge with new volunteers and guide them in their development as professionals in the HR field.",
  },
  {
    linkedin: "https://www.linkedin.com/in/apostolos-nikolaou-635775327/",
    key: 3,
    img: "/apostolos.jpg",
    name: "Apostolos Nikolaou",
    role: "Head of Marketing",
    bio: "I am a graduate of the Department of International and European Studies at the University of Macedonia and the Team Leader of the Marketing team in our organization. As a team leader, I specialize in creating both print and digital promotional materials for INEFAN, while my goal is to continuously support my team members in acquiring knowledge and developing creative content. At the same time, I strive to enhance the organizational skills of the team members to help them understand the needs and dynamics of the marketing sector, as well as to communicate effectively with the broader audience.",
  },
  {
    linkedin: "https://www.linkedin.com/in/niky-papanikolaou/",
    key: 4,
    img: "/niki.jpg",
    name: "Niki Papanikolaou",
    role: "Head of P.M & Fundraising",
    bio: "I am a final-year student at the Faculty of Law at Aristotle University of Thessaloniki and a postgraduate MBA student specializing in Banking & Finance at ACT College. Having served as a Project & Fundraising Manager at TEDxAUTH and the Entrepreneurship Hub at ACT, my experience led me to the equally significant role of team leader in the Project Management & Fundraising team within our organization. In this capacity, my goal is to contribute to the organization's initiatives and share my knowledge and experience with the team members, enhancing collaboration and the effectiveness of our projects.",
  },
  {
    linkedin: "https://www.linkedin.com/in/theodorostsoulfaidis/",
    key: 5,
    img: "/theodoros.jpg",
    name: "Theodoros Tsoulfaidis",
    role: "Head of Financial Analysis",
    bio: "I am in the fourth year of my undergraduate studies in the Department of Economics at Aristotle University of Thessaloniki. With three years of active participation in the INEFAN organization, my academic education, combined with the experience I have gained, led me to take on the role of head of the economic analysis team within our organization. My main goal is to share my knowledge and experience with the team members while continuously developing and refining the skills required for analyzing indicators and variables in national and international markets.",
  },
  {
    linkedin: "https://www.linkedin.com/in/thomas-sioumpalas-77a130231/",
    key: 6,
    img: "/thomas.jpg",
    name: "Thomas Sioumpalas",
    role: "Head of P.M & Fundraising",
    bio: "I am a student in the Department of Accounting and Information Systems at the International Hellenic University, while also working as an accounting assistant at LPC S.A., a member of the Motor Oil Group. My professional experience, combined with the knowledge I acquire from my academic studies, allows me to gain an in-depth understanding of the financial and managerial aspects of the modern business environment. Having been an active member of INEFAN for several years, I now have the honor of co-leading the Project Management & Fundraising team alongside Niki. My primary goal is the continuous expansion of our network of collaborators through strategic partnerships and targeted initiatives that strengthen the organization's impact. At the same time, I focus on the continuous development of team members, with particular emphasis on enhancing their communication and negotiation skills, enabling them to effectively navigate challenges and opportunities in the field of Project Management.",
  },
];

export const articles = [
  {
    category: "international",
    title: "Crises and Turmoil in the Oil Industry",
    subtitle: "The oil industry faces crises and turmoil from geopolitical tensions, price volatility, supply disruptions, regulatory challenges, environmental concerns, trade conflicts, and energy transitions.",
    content: "",
    date: "February 14, 2025",
    picture: "/blog-1.png",
    key: "a1",
    slug: "crises-and-turmoil",
  },
  {
    category: "economics",
    title: "Seeking a New Productive Model",
    subtitle: "Seeking a new productive model involves innovation, efficiency, sustainability, technological advancements, economic resilience, policy reforms, adaptive strategies, and optimized resource allocation for growth.",
    content: "",
    date: "November 29, 2024",
    picture: "/blog-2.jpg",
    key: "a2",
    slug: "seeking-a-new-productive-model",
  },
  {
    category: "economics",
    title: "The Demographic Problem of Greece",
    subtitle: "Greece faces a severe demographic problem due to low birth rates, an aging population, youth emigration, economic challenges, and strained social systems.",
    content: "",
    date: "June 4, 2024",
    picture: "/blog-3.jpg",
    key: "a3",
    slug: "the-demographic-problem-of-greece",
  },
  {
    category: "business",
    title: "Why Sustainable Development? A Case Study of H&M",
    subtitle: "H&M pursues sustainable development through recycling, ethical sourcing, renewable energy, transparency, innovation, circular economy, waste reduction, eco-friendly materials, and responsible production.",
    content: "",
    date: "May 29, 2024",
    picture: "/blog-4.jpg",
    key: "a4",
    slug: "why-sustainable-development",
  },
  {
    category: "international",
    title: "The Economic Consequences of the War in Ukraine",
    subtitle: "The war in Ukraine has triggered global economic instability, supply chain disruptions, energy crises, inflation, food shortages, market volatility, recession risks, and geopolitical tensions.",
    content: "On Thursday, February 24, 2022, Russia invaded Ukraine, disrupting global balances and forever changing the world. This armed conflict, beyond its humanitarian and geopolitical dimensions, has also had a tremendous economic impact, affecting not only the directly involved parties—Russia and Ukraine—but also the global economy, and more specifically the European Union and its member states. The fact that Russia is an energy giant while Ukraine is one of the world's largest exporters of agricultural products only exacerbates the situation, creating a chain of intractable problems. How has the war affected the Ukrainian economy? Ukraine has historically been one of the poorest regions of the Soviet Union. However, after gaining independence in 1991, its economy developed significantly. This progress was abruptly halted by the war, which has shaken the Ukrainian state to its core. Notably, in just the first year of the conflict, the country lost 30-35% of its GDP, marking the deepest recession in its brief history.",
    date: "May 29, 2024",
    picture: "/blog-5.jpg",
    key: "a5",
    slug: "the-economic-consequences-of-the-war",
  },
  {
    category: "international",
    title: "How Demographics Affect China's Economy",
    subtitle: "China's aging population, declining birth rates, and shrinking workforce impact economic growth, productivity, social welfare costs, consumer demand, and long-term sustainability.",
    content: "",
    date: "February 29, 2024",
    picture: "/blog-6.jpg",
    key: "a6",
    slug: "how-demographics-affect-chinas-economy",
  },
];
